# Generated by Django 5.1.7 on 2025-05-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheese",
            name="min_qty_big_opt",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Минимальное количество для крупного опта",
            ),
        ),
        migrations.AddField(
            model_name="cheese",
            name="min_qty_small_opt",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Минимальное количество для мелкого опта",
            ),
        ),
        migrations.AddField(
            model_name="cheese",
            name="price_big_opt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Цена крупный опт",
            ),
        ),
        migrations.AddField(
            model_name="cheese",
            name="price_small_opt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Цена мелкий опт",
            ),
        ),
    ]
