# Generated by Django 5.1.7 on 2025-05-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_batch_batchitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="total_discount_percent",
        ),
    ]
